# Data Anlytics Course Work - 1.6 million UK traffic accidents

## Import Libraries

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from shapely.geometry import Point, Polygon
import geopandas as gpd
import geojsonio

## Read Accidents Data (2005-2007, 2009-2011, 2012-2014)

In [2]:
df1 = pd.read_csv('accidents_2005_to_2007.csv', dtype='unicode')
df2 = pd.read_csv('accidents_2009_to_2011.csv', dtype='unicode')
df3 = pd.read_csv('accidents_2012_to_2014.csv', dtype='unicode')

## Read UK traffic Average Annual Daily Flow and Geo Json

In [12]:
df4 = pd.read_csv('ukTrafficAADF.csv', dtype='unicode')
df5 = pd.read_json('Local_Authority_Districts_Dec_2016.geojson', dtype='unicode')

## Try to draw something from geojson

In [20]:
states = gpd.read_file('Local_Authority_Districts_Dec_2016.geojson')
statesJson = states.to_json()

In [34]:
states.head()

,objectid,lad16cd,lad16nm,lad16nmw,bng_e,bng_n,long,lat,st_areashape,st_lengthshape,geometry
0,1,E06000001,Hartlepool,,447157,531476,-1.27023,54.676159,9.355951e+07,71707.330231,(POLYGON ((-1.268455585200569 54.7261163502866...
1,2,E06000002,Middlesbrough,,451141,516887,-1.21099,54.544670,5.388858e+07,43840.846371,"(POLYGON ((-1.2439036468982 54.58936316454281,..."
2,3,E06000003,Redcar and Cleveland,,464359,519597,-1.00611,54.567520,2.448203e+08,97993.287164,(POLYGON ((-1.137578154500661 54.6458090223704...
3,4,E06000004,Stockton-on-Tees,,444937,518183,-1.30669,54.556911,2.049622e+08,119581.507757,(POLYGON ((-1.317285862199188 54.6448033247461...
4,5,E06000005,Darlington,,428029,515649,-1.56835,54.535351,1.974757e+08,107206.282926,POLYGON ((-1.637677653638193 54.61713779015086...

In [35]:
statesJson = states.head().to_json()
geojsonio.display(statesJson)

'http://geojson.io/#id=gist:/49ac980fab22e655514f714c1f045a5c'

## Figure out data structure from accidents data

In [52]:
pd.options.display.max_columns = 33
df1.sample(5)

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
458461,200720E102003,411790,283970,-1.827942,52.453529,20,3,1,1,19/07/2007,5,17:37,300,E08000025,6,0,Single carriageway,30,NaN,NaN,-1,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,Yes,E01008889,2007
407105,200701XD80367,518560,180570,-0.29289,51.511573,1,3,2,1,08/06/2007,6,08:10,27,E09000009,3,4020,Single carriageway,30,NaN,Giveway or uncontrolled,6,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,No,E01001234,2007
222508,200601ZD30451,532820,163680,-0.093841,51.356617,1,3,1,5,01/06/2006,5,18:35,20,E09000008,4,275,Single carriageway,30,NaN,NaN,-1,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,Yes,E01001040,2006
93190,200522FJ45080,372750,292260,-2.403115,52.527496,22,2,1,1,03/08/2005,4,08:37,279,E06000051,6,0,Single carriageway,60,NaN,Giveway or uncontrolled,6,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,Yes,E01028834,2005
468502,2.01E+12,388710,348390,-2.169814,53.032652,21,3,2,1,26/10/2007,6,21:20,257,E06000021,3,5272,Single carriageway,30,NaN,Giveway or uncontrolled,4,5047,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,Yes,E01014323,2007

Column Name                                    | Description
:---------:                                    | -----------
Accident_Index                                 |Unique ID
Location_Easting_OSGR                          |英國國家網格參考系統 Ordnance Survey National Grid
Location_Northing_OSGR                         |--
Longitude                                      |經度
Latitude                                       |緯度
Police_Force                                   |警力？
Accident_Severity                              |事故嚴重程度
Number_of_Vehicles                             |事故車輛
Number_of_Casualties                           |傷亡人數
Date                                           |日期
Day_of_Week                                    |週數
Time                                           |時分秒
Local_Authority_District                       |？
Local_Authority_Highway                        |？
1st_Road_Class                                 |交叉點：第一條路級別？
1st_Road_Number                                |交叉點：第一條路編號？
Road_Type                                      |路別 e.g. Roundabout, One Way, Dual Carriageway, Single Carriageway
Speed_limit                                    |速限
Junction_Detail                                |交叉點：類型 e.g. Crossroads, Roundabouts, Private Roads
Junction_Control                               |交叉點：交通控制類型 e.g. person, a type of sign, automated
2nd_Road_Class                                 |交叉點：第二條路級別？
2nd_Road_Number                                |交叉點：第二條路編號？
Pedestrian_Crossing-Human_Control              |行人穿越道：號誌 e.g. human controller
Pedestrian_Crossing-Physical_Facilities        |行人穿越道：設施 e.g. zebra crossing, bridge
Light_Conditions                               |照明狀況
Weather_Conditions                             |天氣狀況
Road_Surface_Conditions                        |路面狀況
Special_Conditions_at_Site                     |特別狀況
Carriageway_Hazards                            |道路風險 e.g. a pedestrian, another accident, something in the road?
Urban_or_Rural_Area                            |城市或鄉村區域代碼
Did_Police_Officer_Attend_Scene_of_Accident    |警察是否目擊事故發生
LSOA_of_Accident_Location                      |事故行政區及代碼 (Lower Layer Super Output Areas)
Year                                           |年份

In [44]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570011 entries, 0 to 570010
Data columns (total 33 columns):
Accident_Index                                 570011 non-null object
Location_Easting_OSGR                          569910 non-null object
Location_Northing_OSGR                         569910 non-null object
Longitude                                      569910 non-null object
Latitude                                       569910 non-null object
Police_Force                                   570011 non-null object
Accident_Severity                              570011 non-null object
Number_of_Vehicles                             570011 non-null object
Number_of_Casualties                           570011 non-null object
Date                                           570011 non-null object
Day_of_Week                                    570011 non-null object
Time                                           569944 non-null object
Local_Authority_(District)                     570011 non-null object
Local_Authority_(Highway)                      570011 non-null object
1st_Road_Class                                 570011 non-null object
1st_Road_Number                                570011 non-null object
Road_Type                                      570011 non-null object
Speed_limit                                    570011 non-null object
Junction_Detail                                0 non-null object
Junction_Control                               333066 non-null object
2nd_Road_Class                                 570011 non-null object
2nd_Road_Number                                570011 non-null object
Pedestrian_Crossing-Human_Control              569994 non-null object
Pedestrian_Crossing-Physical_Facilities        569977 non-null object
Light_Conditions                               570011 non-null object
Weather_Conditions                             569991 non-null object
Road_Surface_Conditions                        569349 non-null object
Special_Conditions_at_Site                     570000 non-null object
Carriageway_Hazards                            569988 non-null object
Urban_or_Rural_Area                            570011 non-null object
Did_Police_Officer_Attend_Scene_of_Accident    567636 non-null object
LSOA_of_Accident_Location                      522500 non-null object
Year                                           570011 non-null object
dtypes: object(33)
memory usage: 143.5+ MB

In [47]:
df1.describe()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
count,570011,569910,569910,569910,569910,570011,570011,570011,570011,570011,...,569977,570011,569991,569349,570000,569988,570011,567636,522500,570011
unique,366193,46295,65383,467245,453368,51,3,21,34,1095,...,6,5,9,5,8,6,3,2,33773,3
top,2.01E+12,533650,181050,-0.977611,52.949719,1,3,2,1,21/10/2005,...,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,None,None,1,Yes,E01000004,2005
freq,203663,116,117,41,41,73899,487161,336662,432213,822,...,486482,414282,454074,389897,555325,558858,360761,459311,892,198735

## Figure out data structure from AADF

In [53]:
df4.sample(5)

,AADFYear,CP,Estimation_method,Estimation_method_detailed,Region,LocalAuthority,Road,RoadCategory,Easting,Northing,StartJunction,EndJunction,LinkLength_km,LinkLength_miles,PedalCycles,Motorcycles,CarsTaxis,BusesCoaches,LightGoodsVehicles,V2AxleRigidHGV,V3AxleRigidHGV,V4or5AxleRigidHGV,V3or4AxleArticHGV,V5AxleArticHGV,V6orMoreAxleArticHGV,AllHGVs,AllMotorVehicles,Lat,Lon
164181,2010,27328,Estimated,Estimated using previous year's AADF on this link,North West,Blackpool,A587,PU,331500,442400,A584,LA Boundary,0.6,0.37,111,142,14409,359,1627,348,37,11,12,13,6,427,16964,53.87326154,-3.04332007
100688,2013,80446,Estimated,Estimated using previous year's AADF on this link,Scotland,Glasgow City,M8,TM,258000,664720,A8,M8 Slips,0.5,0.31,0,287,69952,856,12045,2294,314,325,43,1407,370,4752,87892,55.85470041,-4.270036671
242071,2009,46701,Estimated,Estimated using previous year's AADF on this link,East of England,Suffolk,A134,PR,593740,239000,B1087,A1071,7.7,4.78,11,86,6212,34,1220,225,39,32,33,63,53,445,7997,52.01559335,0.821881556
204804,2008,17176,Estimated,Estimated using previous year's AADF on this link,London,Barnet,A504,PU,522400,188500,Herbert Rd,A41,1,0.62,43,144,12944,411,1368,147,16,10,1,3,0,177,15044,51.58207679,-0.234843643
4491,2003,36603,Estimated,Estimated using previous year's AADF on this link,Yorkshire and the Humber,Leeds,A58,PU,428000,432300,A6110,A62,1.9,1.18,60,121,11316,240,2635,195,27,51,8,12,11,304,14616,53.78627344,-1.576508247

In [42]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275385 entries, 0 to 275384
Data columns (total 29 columns):
AADFYear                      275385 non-null object
CP                            275385 non-null object
Estimation_method             237812 non-null object
Estimation_method_detailed    237812 non-null object
Region                        275385 non-null object
LocalAuthority                275385 non-null object
Road                          275385 non-null object
RoadCategory                  275385 non-null object
Easting                       275385 non-null object
Northing                      275385 non-null object
StartJunction                 275129 non-null object
EndJunction                   275147 non-null object
LinkLength_km                 275385 non-null object
LinkLength_miles              275385 non-null object
PedalCycles                   275385 non-null object
Motorcycles                   275385 non-null object
CarsTaxis                     275385 non-null object
BusesCoaches                  275385 non-null object
LightGoodsVehicles            275385 non-null object
V2AxleRigidHGV                275385 non-null object
V3AxleRigidHGV                275385 non-null object
V4or5AxleRigidHGV             275385 non-null object
V3or4AxleArticHGV             275385 non-null object
V5AxleArticHGV                275385 non-null object
V6orMoreAxleArticHGV          275385 non-null object
AllHGVs                       275385 non-null object
AllMotorVehicles              275385 non-null object
Lat                           275385 non-null object
Lon                           275385 non-null object
dtypes: object(29)
memory usage: 60.9+ MB

In [48]:
df4.describe()

,AADFYear,CP,Estimation_method,Estimation_method_detailed,Region,LocalAuthority,Road,RoadCategory,Easting,Northing,...,V2AxleRigidHGV,V3AxleRigidHGV,V4or5AxleRigidHGV,V3or4AxleArticHGV,V5AxleArticHGV,V6orMoreAxleArticHGV,AllHGVs,AllMotorVehicles,Lat,Lon
count,275385,275385,237812,237812,275385,275385,275385,275385,275385,275385,...,275385,275385,275385,275385,275385,275385,275385,275385,275385,275385
unique,17,17616,2,5,11,190,1719,8,11126,12673,...,4952,1222,1359,1925,5425,5666,12243,58619,17858,17858
top,2015,47958,Estimated,Estimated using previous year's AADF on this link,Scotland,Kent,A1,PU,430000,190000,...,151,22,0,2,0,0,192,11304,55.83447982,-3.408870613
freq,16504,17,175404,159510,38172,7417,3598,134655,936,707,...,682,3672,6295,10124,8936,13112,381,26,34,34

|Column Name|Description|Type|
|:---:|---|:---:|
|AADFYear|The year data was recorded.|Numeric|
|CP|Count point. A unique reference for the road link that links the AADFs to the road network.|Numeric|
|Estimation_method|Counted or estimated.|String|
|Estimation_method_detailed|How it was counted, or how it was estimated.|String|
|Region|11 regions, essentially Wales, Scotland and then 9 English regions. No data from N.Ireland.|String|
|LocalAuthority|Breaking down the regions further.|String|
|Road|Roads are either M for Motorway (the biggest roads), or A which are our major roads. B roads aren't included.|String|
|RoadCategory|PM for M or Class A Principal Motorway, PR for Class A Principal Road in Rural Area, PU for Class A Principal Road in Urban Area, TM for M or Class A Trunk Motorway, TR for Class A Trunk Road in Rural Area, TU for Class A Trunk Road in Urban Area.|String|
|Easting|UK local coordinate grid reference.|Numeric|
|Northing|UK local coordinate grid reference.|Numeric|
|StartJunction|Where the stretch of road begins.|Numeric|
|EndJunction|Where the stretch ends.|Numeric|
|LinkLength_km|How far between the start and end (km).|Numeric|
|LinkLength_miles|How far between the start and end (mi).|Numeric|
|PedalCycles|Average volume per day for pedaled vehicles.|Numeric|
|Motorcycles|Average volume per day for motorcycles.|Numeric|
|CarsTaxis|Average volume per day for cars and and taxis.|Numeric|
|BusesCoaches|Average volume per day for buses and coaches.|Numeric|
|LightGoodsVehicles|Average volume per day for light trucks.|Numeric|
|V2AxleRigidHGV|Average volume per day for two-axle rigid-bodied heavy trucks.|Numeric|
|V3AxleRigidHGV|Average volume per day for three-axle rigid-bodied heavy trucks.|Numeric|
|V4or5AxleRigidHGV|Average volume per day for four-or-five-axle rigid-bodied heavy trucks.|Numeric|
|V3or4AxleArticHGV|Average volume per day for three-or-four-axle articulated heavy trucks.|Numeric|
|V5AxleArticHGV|Average volume per day for five-axle articulated heavy trucks.|Numeric|
|V6orMoreAxleArticHGV|Average volume per day for six-axle-or-greater articulated heavy trucks.|Numeric|
|AllHGVs|All heavy good vehicles (HVGs). Sum of all the previous HGV fields.|Numeric|
|AllMotorVehicles|AADT for the sum of all motor vehicles.|Numeric|
|Lat|Latitude.|Numeric|
|Lon|Longitude.|Numeric|

In [ ]:
df